title: Arslan Shahid
description: Hey! I am Arslan Shahid a graduate student with passion for bridging research and engineering to build reliable AI/ML systems. Write me at arslan.shahid65@yahoo.com
theme: jekyll-theme-minimal
